import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "bn" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  bn: {
    "home": "হোম",
    "lang": "bn",
    "shop": "শপ",
    "combo": "কম্বো",
    "reviews": "রিভিউ",
    "cart": "কার্ট",
    "checkout": "চেকআউট",
    "buy_now": "এখনই কিনুন",
    "add_to_cart": "কার্টে যোগ করুন",
    "search": "খুঁজুন",
    "contact": "যোগাযোগ",
    "shipping_policy": "শিপিং পলিসি",
    "return_policy": "রিটার্ন পলিসি",
    "follow_us": "আমাদের অনুসরণ করুন",
    "company": "কোম্পানি",
    "address": "ঠিকানা",
    "all_categories": "সকল ক্যাটাগরি",
    "quick_links": "কুইক লিঙ্ক",
    "secure_checkout": "১০০% নিরাপদ চেকআউট",
    "order_now": "অর্ডার করুন",
    "free_shipping": "ফ্রি শিপিং",
    "premium_quality": "প্রিমিয়াম কোয়ালিটি",
    "customer_support": "কাস্টমার সাপোর্ট",
    "view_details": "বিস্তারিত দেখুন",
    "out_of_stock": "স্টক আউট",
    "subtotal": "সাবটোটাল",
    "total": "মোট",
    "tax": "ভ্যাট/ট্যাক্স",
    "discount": "ডিসকাউন্ট",
    "shop_now": "শপিং শুরু করুন",
    "learn_more": "আরও জানুন",
    "copyright": "সর্বস্বত্ব সংরক্ষিত।",
    "privacy_policy": "প্রাইভেসি পলিসি",
    "terms_conditions": "টার্মস এন্ড কন্ডিশন",
    "satisfied_customers": "সন্তুষ্ট কাস্টমার",
    "products_delivered": "পণ্য ডেলিভারি",
    "fast_delivery": "দেশজুড়ে ফাস্ট ডেলিভারি",
    "original_products": "১০০% অরিজিনাল পণ্য",
    "cash_on_delivery": "ক্যাশ অন ডেলিভারি",
    "delivery_dhaka": "ঢাকার ভেতরে দ্রুত ডেলিভারি",
    "damage_replace": "ড্যামেজ রিপ্লেস",
    "happy_customers": "সন্তুষ্ট কাস্টমার",
    "admin_panel": "অ্যাডমিন প্যানেল",
    "see_details": "বিস্তারিত দেখুন",
    "my_account": "আমার অ্যাকাউন্ট",
    "shopping_cart": "শপিং কার্ট",
    "product_suggestions": "প্রোডাক্ট সাজেশন",
    "searching": "খুঁজছি...",
    "no_products_found": "কোনো প্রোডাক্ট পাওয়া যায়নি",
    "view_all_results": "সকল ফলাফল দেখুন",
    "search_placeholder": "আপনার পছন্দের প্রোডাক্ট খুঁজুন...",
    "decor_dream_space": "আপনার স্বপ্নের ঘর",
    "system_status": "সিস্টেম স্ট্যাটাস",
    "all_services_active": "সব সার্ভিস সচল আছে",
    "packing_operations": "প্যাকিং অপারেশন",
    "orders_ready": "অর্ডার প্রস্তুত করুন",
    "start_packing": "প্যাকিং শুরু করুন",
    "verification_queue": "ভেরিফিকেশন কিউ",
    "pending_orders": "অর্ডার যাচাই করুন",
    "verify_orders": "অর্ডার ভেরিফাই করুন",
    "recent_orders": "সাম্প্রতিক অর্ডার",
    "latest_orders": "সর্বশেষ অর্ডারসমূহ",
    "view_all": "সব দেখুন",
    "order": "অর্ডার",
    "customer": "কাস্টমার",
    "date": "তারিখ",
    "total_label": "মোট",
    "status": "স্টাটাস",
    "pending": "প্রতীক্ষায়",
    "confirmed": "কনফার্মড",
    "processing": "প্রসেসিং",
    "shipped": "শিপড",
    "delivered": "ডেলিভারড",
    "cancelled": "ক্যান্সেলড",
    "returned": "রিটার্ন",
    "today_orders": "আজকের অর্ডার",
    "today_revenue": "আজকের আয়",
    "total_revenue": "মোট আয়",
    "monthly_revenue": "মাসিক আয়",
    "total_products": "মোট প্রোডাক্ট",
    "out_of_stock_kpi": "স্টক আউট",
    "courier_balance": "কুরিয়ার ব্যালেন্স",
    "live": "লাইভ",
    "sales_graph": "বিক্রয় গ্রাফ",
    "revenue_trend": "আয়ের প্রবণতা",
    "days": "দিন",
    "order_status": "অর্ডার স্ট্যাটাস",
    "distribution": "বন্টন",
    "order_summary": "অর্ডার সামারি",
    "all_statuses": "সকল স্ট্যাটাস",
    "top_selling": "সেরা প্রোডাক্ট",
    "best_products": "সবচেয়ে বেশি বিক্রিত",
    "no_data": "কোনো তথ্য নেই",
    "sold": "বিক্রিত",
    "morning": "শুভ সকাল",
    "afternoon": "শুভ অপরাহ্ন",
    "evening": "শুভ সন্ধ্যা",
    "logout": "লগ আউট",
    "access_denied": "প্রবেশাধিকার সংরক্ষিত",
    "access_denied_desc": "এই পৃষ্ঠাটি দেখার জন্য আপনার পর্যাপ্ত অনুমতি নেই। দয়া করে সুপার অ্যাডমিনের সাথে যোগাযোগ করুন।",
    "return_to_dashboard": "ড্যাশবোর্ডে ফিরে যান",
    "super_admin_label": "সুপার অ্যাডমিন",
    "admin_label": "অ্যাডমিন",
    "moderator_label": "মডারেটর",
    "production_label": "প্রোডাকশন",
    "main_menu": "প্রধান মেনু",
    "dashboard": "ড্যাশবোর্ড",
    "orders": "অর্ডারসমূহ",
    "all_orders": "সকল অর্ডার",
    "incomplete_orders": "ইনকমপ্লিট অর্ডার",
    "products": "প্রোডাক্টস",
    "combo_offers": "কম্বো অফারগুলো",
    "combo_management": "কম্বো ম্যানেজমেন্ট",
    "total_bundles_listed": "মোট {count}টি কম্বো তালিকাভুক্ত",
    "new_combo": "নতুন কম্বো",
    "combo_info": "কম্বো তথ্য",
    "product_count": "প্রোডাক্ট",
    "price_taka": "মূল্য (৳)",
    "active_listings": "সক্রিয় প্রোডাক্ট",
    "stock_warnings": "স্টক আউট",
    "combo_revenue": "কম্বো রেভিনিউ",
    "categories": "ক্যাটাগরি",
    "notifications": "নোটিফিকেশন",
    "inventory": "ইনভেন্টরি",
    "finance": "ফাইন্যান্স",
    "visitor_tracking": "ভিজিটর ট্র্যাকিং",
    "marketing_customers": "মার্কেটিং ও কাস্টমার",
    "marketing": "মার্কেটিং",
    "coupons": "কুপন",
    "customers": "কাস্টমার",
    "system_settings": "সিস্টেম ও সেটিংস",
    "settings": "সেটিংস",
    "team_management": "টিম ম্যানেজমেন্ট",
    "team_members": "টিম মেম্বার",
    "departments": "ডিপার্টমেন্ট",
    "courier_management": "কুরিয়ার ম্যানেজমেন্ট",
    "fraud_checker": "ফ্রড চেকার",
    "order_management": "অর্ডার ম্যানেজমেন্ট",
    "live_transaction_stream": "রিয়েল-টাইম ট্রানজ্যাকশন মনিটর করুন",
    "export": "রপ্তানি",
    "dispatch": "ডিসপ্যাচ",
    "search_orders": "অর্ডার খুঁজুন...",
    "all_payments": "সকল পেমেন্ট",
    "cod": "সিওডি",
    "bkash": "বিকাশ",
    "selected": "সিলেক্টেড",
    "bulk_actions": "বাল্ক অ্যাকশন",
    "confirm_selected": "কনফার্ম সিলেক্টেড",
    "processing_selected": "প্রসেসিং সিলেক্টেড",
    "delete_selected": "ডিলিট সিলেক্টেড",
    "action": "আকশন",
    "cancel_btn": "বাতিল করুন",
    "print": "প্রিন্ট",
    "pack_order": "প্যাকিং করুন",
    "send_to_courier": "কুরিয়ারে পাঠাও",
    "select_courier": "কুরিয়ার সিলেক্ট করুন:",
    "book_now": "বুক করুন",
    "track": "ট্র্যাকিং",
    "ship_order": "শিপিং করুন",
    "recover": "পুনরুদ্ধার",
    "invoice": "ইনভয়েস",
    "edit": "সম্পাদনা",
    "call": "কল",
    "order_details": "অর্ডারের বিবরণ",
    "items_manifest": "পণ্যের তালিকা",
    "units": "টি",
    "operational_timeline": "অপারেশনাল টাইমলাইন",
    "active_stage": "চলমান পর্যায়",
    "identity_profile": "পরিচয় প্রোফাইল",
    "logistics_hub": "লজিস্টিক হাব",
    "destination_address": "গন্তব্য ঠিকানা",
    "view_on_satellite": "ম্যাপে দেখুন",
    "financial_settlement": "আর্থিক হিসাব",
    "freight": "শিপিং চার্জ",
    "total_settlement": "সর্বমোট বিল",
    "internal_operational_logs": "অভ্যন্তরীণ অপারেশনাল লগ",
    "system_log_entry": "সিস্টেম লগ এন্ট্রি...",
    "abort_view": "দেখা বন্ধ করুন",
    "authorize_order": "অর্ডার অনুমোদন করুন",
    "terminate_order": "অর্ডার টার্মিনেট করুন",
    "failed_load_orders": "অর্ডার লোড করতে ব্যর্থ",
    "updating_orders": "অর্ডার আপডেট হচ্ছে...",
    "orders_updated": "টি অর্ডার আপডেট করা হয়েছে",
    "bulk_update_failure": "বাল্ক আপডেট ব্যর্থ হয়েছে",
    "confirm_bulk_delete": "আপনি কি নিশ্চিতভাবে এই অর্ডারগুলো মুছে ফেলতে চান?",
    "deleting_orders": "অর্ডার মুছে ফেলা হচ্ছে...",
    "orders_deleted": "অর্ডার মুছে ফেলা হয়েছে",
    "delete_failure": "মুছে ফেলতে ব্যর্থ",
    "manager_role_required": "ম্যানেজারিয়াল রোল প্রয়োজন",
    "order_status_success": "অর্ডার স্ট্যাটাস সফলভাবে আপডেট করা হয়েছে",
    "order_update_success": "অর্ডার আপডেট সফল হয়েছে",
    "delete_order_confirm": "অর্ডারটি চিরতরে মুছে ফেলতে চান?",
    "order_deleted_success": "অর্ডারটি মুছে ফেলা হয়েছে",
    "delete_failed": "মুছে ফেলা সম্ভব হয়নি",
    "order_recovered_success": "অর্ডারটি পুনরুদ্ধার করা হয়েছে",
    "booking_to_courier": "এ বুক করা হচ্ছে...",
    "booking_success": "সফল! ট্র্যাকিং:",
    "booking_failed": "বুকিং ব্যর্থ হয়েছে",
    "verification_protocol_desc": "অর্ডার যাচাইকরণ প্রক্রিয়া",
    "note_optional": "নোট (ঐচ্ছিক)",
    "hold": "হোল্ড",
    "void_security_protocol": "সিকিউরিটি প্রোটোকল বাতিল",
    "revocation_justification": "বাতিল করার কারণ",
    "abort_request": "অনুরোধ বাতিল করুন",
    "void_transaction": "লেনদেন বাতিল করুন",
    "courier_dispatch_center": "কুরিয়ার ডিসপ্যাচ সেন্টার",
    "operational_gateway": "অপারেশনাল গেটওয়ে",
    "operational_manifest": "অপারেশনাল মেনিফেস্ট",
    "transmit_to_gateway": "গেটওয়েতে পাঠান",
    "order_ready_count": "টি অর্ডার প্রস্তুত",
    "dispatching_to": "এ ডিসপ্যাচ হচ্ছে...",
    "dispatch_success": "সফলভাবে ডিসপ্যাচ করা হয়েছে",
    "bulk_dispatch_failed": "বাল্ক ডিসপ্যাচ ব্যর্থ হয়েছে",
    "terminate_order_confirm_pre": "আপনি কি নিশ্চিতভাবে",
    "permanently_decommission": "স্থায়ীভাবে বাতিল",
    "revocation_justification_placeholder": "বাতিল করার অপারেশনাল কারণ উল্লেখ করুন...",
    "dispatch_warning_pre": "ডিসপ্যাচ শুরু করলে সকল",
    "dispatch_warning_mid": "অর্ডার",
    "dispatch_warning_post": "গেটওয়েতে প্রেরিত হবে। প্রেরণের আগে গ্রাহকের তথ্য যাচাই করুন।",
    "product_management": "প্রোডাক্ট ম্যানেজমেন্ট",
    "total_products_live": "মোট {count}টি প্রোডাক্ট তালিকাভুক্ত",
    "new_product": "নতুন প্রোডাক্ট",
    "total_items": "মোট আইটেম",
    "draft_archived": "ড্রাফট / আর্কাইভ",
    "search_catalog": "প্রোডাক্ট নাম, SKU বা আইডি সার্চ করুন...",
    "all": "সব",
    "add_new_product": "নতুন পণ্য যোগ করুন",
    "product_details_desc": "আপনার পণ্যের বিস্তারিত তথ্য দিন",
    "product_images": "পণ্যের ছবি",
    "ratio_hint": "সেরা রেজাল্টের জন্য ১:১ অনুপাতের ছবি ব্যবহার করুন",
    "upload_image": "ছবি আপলোড করুন",
    "drag_drop_hint": "বা ছবি ড্র্যাগ করে এখানে ফেলুন",
    "primary_image": "প্রধান ছবি",
    "product_info": "পণ্যের তথ্য",
    "product_name": "পণ্যের নাম",
    "brand_optional": "ব্র্যান্ড (ঐচ্ছিক)",
    "model_sku_optional": "মডেল / কোড (ঐচ্ছিক)",
    "short_description": "সংক্ষিপ্ত বিবরণ",
    "detailed_description": "বিস্তারিত বিবরণ",
    "pricing": "মূল্য নির্ধারণ",
    "old_price_optional": "পুরাতন মূল্য (ঐচ্ছিক)",
    "discount_percentage": "ছাড়ের শতাংশ (%)",
    "stock_inventory": "স্টক ও ইনভেন্টরি",
    "stock_amount": "স্টক পরিমাণ",
    "alert_level": "অ্যালার্ট লেভেল",
    "hide_out_of_stock_hint": "স্টক সীমিত (Out of stock হলে দেখাবেন না)",
    "product_attributes": "পণ্যের বৈশিষ্ট্য",
    "size_optional": "সাইজ (ঐচ্ছিক)",
    "color_optional": "রং (ঐচ্ছিক)",
    "weight_optional": "ওজন (ঐচ্ছিক)",
    "add_more_attributes": "আরো বৈশিষ্ট্য যোগ করুন",
    "product_tags_optional": "পণ্যের ট্যাগ (ঐচ্ছিক)",
    "tag_hint": "যেমন: ইসলামিক, ক্যানভাস, ওয়াল আর্ট",
    "landing_page_customization": "ল্যান্ডিং পেজ কাস্টমাইজেশন",
    "top_banner_text_label": "টপ ব্যানার টেক্সট",
    "whats_included_combo": "কম্বোতে যা যা থাকছে",
    "package_contents_sidebar": "প্যাকেজে যা যা থাকবে (Sidebar)",
    "save_product": "পণ্য সংরক্ষণ করুন",
    "product_saved_success": "প্রোডাক্ট সফলভাবে সেভ করা হয়েছে",
    "product": "প্রোডাক্ট",
    "category": "ক্যাটাগরি",
    "price": "মূল্য",
    "stock": "স্টক",
    "view_on_store": "স্টোরে দেখুন",
    "product_delete_confirm": "আপনি কি নিশ্চিতভাবে এই প্রোডাক্টটি ডিলিট করতে চান?",
    "status_active_success": "সক্রিয় করা হয়েছে",
    "status_inactive_success": "নিষ্ক্রিয় করা হয়েছে",
    "type": "প্রকার",
    "sku": "SKU",
    "footer_desc_fallback": "প্রিমিয়াম কোয়ালিটি এবং আধুনিক ডিজাইনের সংমিশ্রণে আপনার লাইফস্টাইলকে করুন আরও সুন্দর ও সহজ।",
    "dhaka_bangladesh": "ঢাকা, বাংলাদেশ",
    "categories_title": "ক্যাটাগরি",
    "settings_title": "সেটিংস",
    "helpline": "হেল্পলাইন",
    "whatsapp_chat": "হোয়াটসঅ্যাপ চ্যাট",
    "login_welcome": "স্বাগতম!",
    "login_admin_panel": "অ্যাডমিন প্যানেল",
    "login_desc": "আপনার স্টোর পরিচালনা করার জন্য অ্যাডমিন প্যানেলে লগইন করুন। আপনার ড্যাশবোর্ডে অ্যাক্সেস পেতে সঠিক তথ্য প্রদান করুন।",
    "feature_control_title": "সম্পূর্ণ নিয়ন্ত্রণ",
    "feature_control_desc": "আপনার স্টোরের প্রতিটি দিক পরিচালনা করুন সহজেই।",
    "feature_fast_title": "দ্রুত ব্যবস্থাপনা",
    "feature_fast_desc": "অর্ডার এবং পণ্য পরিচালনা করুন মুহূর্তের মধ্যে।",
    "feature_secure_title": "নিরাপদ প্ল্যাটফর্ম",
    "feature_secure_desc": "আপনার তথ্য এবং লেনদেন সবসময় সুরক্ষিত।",
    "feature_support_title": "২৪/৭ সাপোর্ট",
    "feature_support_desc": "যেকোনো প্রয়োজনে আমরা আপনার পাশে আছি।",
    "failed_to_load_dashboard_data": "ড্যাশবোর্ড ডাটা লোড করতে ব্যর্থ হয়েছে",
    "on_hold": "অপেক্ষমান",
    "total_inventory": "মোট ইনভেন্টরি",
    "confirm_delete": "আপনি কি নিশ্চিত যে আপনি এটি ডিলিট করতে চান?",
    "saving_changes": "পরিবর্তনগুলো সেভ হচ্ছে...",
    "settings_save_success": "সেটিংস সফলভাবে সেভ করা হয়েছে",
    "settings_save_error": "সেটিংস সেভ করতে ব্যর্থ হয়েছে",
    "discard_changes": "পরিবর্তনগুলো বাতিল করুন",
    "hero_section": "হিরো সেকশন",
    "trust_badges": "ট্রাস্ট ব্যাজ",
    "cta_banner": "কল টু অ্যাকশন (CTA)",
    "categories_section": "ক্যাটাগরি সেকশন",
    "main_headline": "প্রধান হেডলাইন",
    "sub_headline": "সাব হেডলাইন",
    "cta_text": "সিটিএ টেক্সট",
    "cta_link": "সিটিএ লিংক",
    "trust_badge_1": "ট্রাস্ট ব্যাজ ১",
    "trust_badge_2": "ট্রাস্ট ব্যাজ ২",
    "trust_badge_3": "ট্রাস্ট ব্যাজ ৩",
    "banner_headline": "ব্যানার হেডলাইন",
    "banner_subline": "ব্যানার সাবলাইন",
    "banner_cta": "ব্যানার সিটিএ",
    "banner_link": "ব্যানার লিংক",
    "section_title": "সেকশন টাইটেল",
    "section_subtitle": "সেকশন সাবটাইটেল",
    "fraud_prevention_system": "ফ্রড প্রতিরোধ সিস্টেম",
    "fraud_prevention_desc": "এই ফিল্টারগুলো ভুয়া অর্ডার ব্লক করতে সাহায্য করে। সতর্কতার সাথে কনফিগার করুন।",
    "success_rate_filters": "সাকসেস রেট ফিল্টার",
    "delivery_success_filter": "ডেলিভারি সাকসেস ফিল্টার",
    "verify_courier_history": "কুরিয়ার ডেলিভারি হিস্টোরি যাচাই",
    "min_success_rate": "সর্বনিম্ন সাকসেস রেট (%)",
    "auto_confirmation": "অটো অর্ডার কনফার্ম",
    "auto_confirmation_desc": "হাই সাকসেস রেট গ্রাহকদের জন্য",
    "operational_security": "অপারেশনাল সিকিউরিটি",
    "external_links_tracking": "এক্সটার্নাল লিঙ্ক ও ট্র্যাকিং",
    "tracking_page_url": "অর্ডার ট্র্যাকিং পেজ URL",
    "terms_conditions_url": "টার্মস ও কন্ডিশন URL",
    "admin_command": "অ্যাডমিন কমান্ড",
    "customer_suite": "কাস্টমার এনগেজমেন্ট",
    "internal_signals": "ইন্টারনাল সিগন্যাল",
    "dashboard_telemetry": "ড্যাশবোর্ড টেলিমেট্রি",
    "order_notifications": "অর্ডার নোটিফিকেশন",
    "new_signal_alerts": "নতুন সিগন্যাল অ্যালার্ট",
    "system_alerts": "সিস্টেম অ্যালার্ট",
    "critical_engine_status": "ক্রিটিক্যাল ইঞ্জিন স্ট্যাটাস",
    "external_relay": "এক্সটারনাল রিলে",
    "multichannel_dispatch": "মাল্টি-চ্যানেল ডিসপ্যাচ",
    "email_distribution": "ইমেইল ডিস্ট্রিবিউশন",
    "sms_dispatch": "এসএমএস ডিসপ্যাচ",
    "engagement_suite": "এনগেজমেন্ট সুইট",
    "communication_matrix": "কমিউনিকেশন ম্যাট্রিক্স",
    "order_placed": "অর্ডার প্লেসড",
    "order_placed_desc": "অর্ডার করার সাথে সাথে",
    "order_confirmed": "অর্ডার কনফার্ম",
    "order_confirmed_desc": "অর্ডার ভেরিফাই করার পর",
    "order_shipped": "অর্ডার শিপড",
    "order_shipped_desc": "কুরিয়ারে হ্যান্ডওভার করলে",
    "out_for_delivery": "আউট ফর ডেলিভারি",
    "out_for_delivery_desc": "ডেলিভারি রাইডার কল করলে",
    "sms_alert": "SMS অ্যালার্ট",
    "email_relay": "ইমেইল রিলে",
    "dispatch_template": "ডিসপ্যাচ টেমপ্লেট",
    "message_content_placeholder": "মেসেজ কন্টেন্ট লিখুন...",
    "campaigns": "ক্যাম্পেইন",
    "audience_hub": "অডিয়েন্স হাব",
    "studio": "স্টুডিও",
    "intelligence": "ইন্টেলিজেন্স",
    "launch_campaign": "লঞ্চ ক্যাম্পেইন",
    "audience": "অডিয়েন্স",
    "message": "মেসেজ",
    "preview": "প্রিভিউ",
    "publish": "পাঠান",
    "campaign_identity": "ক্যাম্পেইন আইডেন্টিটি",
    "campaign_title_placeholder": "ক্যাম্পেইন টাইটেল লিখুন...",
    "sms_protocol": "এসএমএস প্রোটোকল",
    "whatsapp_engine": "হোয়াটসঅ্যাপ ইঞ্জিন",
    "target_segment": "টার্গেট সেগমেন্ট",
    "broadcast_all": "সবাইকে পাঠান (১,২৪০ কাস্টমার)",
    "creative_copy": "ক্রিয়েটিভ কপি",
    "compose_msg_placeholder": "আপনার ক্যাম্পেইন মেসেজ লিখুন...",
    "dynamic_tokens": "ডায়নামিক সিগন্যাল টোকেন",
    "dispatch_now": "এখনই পাঠান",
    "schedule": "শিডিউল",
    "ready_dispatch": "পাঠানোর জন্য প্রস্তুত",
    "abort_wizard": "অ্যাবোর্ট উইজার্ড",
    "go_back": "পিছনে যান",
    "launch_engine": "লঞ্চ ইঞ্জিন",
    "continue": "পরবর্তী ধাপ",
    "audience_engine": "অডিয়েন্স ইঞ্জিন",
    "targeting_params": "গ্লোবাল টার্গেটিং প্যারামিটার",
    "purchase_category": "ক্রয় ক্যাটাগরি",
    "order_volume": "অর্ডার ভলিউম",
    "last_activity": "শেষ অ্যাক্টিভিটি",
    "geo_location": "জিও লোকেশন",
    "success_index": "সাকসেস ইনডেক্স",
    "generate_segment": "সেগমেন্ট জেনারেট করুন",
    "customer_segment": "কাস্টমার সেগমেন্ট",
    "target_cluster": "টার্গেট ক্লাস্টার",
    "content_studio": "কনটেন্ট স্টুডিও",
    "active_templates": "সক্রিয় টেমপ্লেট স্কিমা",
    "init_template": "টেমপ্লেট শুরু করুন",
    "whatsapp_protocol": "হোয়াটসঅ্যাপ প্রোটোকল",
    "block_vpx_users": "ভিপিএন ব্যবহারকারী ব্লক করুন",
    "vpx_desc": "অর্ডার করার সময় ভিপিএন ব্যবহারকারীদের বাধা দিন",
    "block_duplicate_orders": "ডুপ্লিকেট অর্ডার ব্লক করুন",
    "duplicate_desc": "একই সময় একাধিক অর্ডার করা থেকে বিরত রাখুন",
    "duplicate_window_minutes": "ডুপ্লিকেট উইন্ডো (মিনিট)",
    "media_library": "মিডিয়া লাইব্রেরি",
    "store_customize": "স্টোর কাস্টমাইজ",
    "delete_success": "সফলভাবে ডিলিট করা হয়েছে",
    "total_payable": "মোট প্রদেয়",
    "select_items": "আইটেম সিলেক্ট করুন",
    "update_failure": "আপডেট করতে ব্যর্থ হয়েছে",
    "product_deleted_success": "প্রোডাক্ট সফলভাবে ডিলিট করা হয়েছে",
    "settings_load_failed": "সেটিংস লোড করতে ব্যর্থ হয়েছে",
    "settings_save_failed": "সেটিংস সেভ করতে ব্যর্থ হয়েছে",
    "save_changes": "পরিবর্তনগুলো সেভ করুন",
    "upload_success": "আপলোড সফল হয়েছে",
    "banner_slides": "ব্যানার স্লাইডগুলো",
    "slide": "স্লাইড",
    "badge_text": "ব্যাজ টেক্সট",
    "title": "টাইটেল",
    "sub_text": "সাব টেক্সট",
    "btn1_text": "বাটন ১ টেক্সট",
    "btn2_text": "বাটন ২ টেক্সট",
    "image_url": "ইমেজ URL",
    "layout": "লেআউট",
    "left": "বাম",
    "right": "ডান",
    "add_slide": "স্লাইড যোগ করুন",
    "hero_text_customization": "হিরো টেক্সট কাস্টমাইজেশন",
    "credibility_indicators": "নির্ভরযোগ্যতার সূচক",
    "add_badge": "ব্যাজ যোগ করুন",
    "category_section": "ক্যাটাগরি সেকশন",
    "show_categories": "ক্যাটাগরি দেখান",
    "display_on_homepage": "হোমপেজে প্রদর্শন করুন",
    "featured_products": "ফিচারড প্রোডাক্ট",
    "highlighted_products": "হাইলাইটেড প্রোডাক্টগুলো",
    "show_featured": "ফিচারড দেখান",
    "special_products_highlight": "বিশেষ প্রোডাক্ট হাইলাইট",
    "combo_section": "কম্বো সেকশন",
    "show_combo": "কম্বো দেখান",
    "display_combo_offers": "কম্বো অফার প্রদর্শন করুন",
    "why_choose_us": "কেন আমাদের বেছে নেবেন",
    "benefits": "সুবিধাগুলো",
    "photo_gallery": "ফটো গ্যালারি",
    "customer_photos": "গ্রাহকদের ছবি",
    "customer_feedback": "গ্রাহকদের মতামত",
    "islamic_quote": "ইসলামিক বাণী",
    "wisdom_text": "প্রজ্ঞা ও অনুপ্রেরণা",
    "bottom_banner": "শেষ সেকশন",
    "admin_login_header": "অ্যাডমিন লগইন",
    "login_to_account": "আপনার অ্যাকাউন্টে প্রবেশ করুন",
    "email_mobile": "ইমেইল বা ইউজারনেম",
    "email_mobile_placeholder": "আপনার ইমেইল বা ইউজারনেম দিন",
    "password_label": "পাসওয়ার্ড",
    "password_placeholder": "••••••••",
    "remember_me": "মনে রাখুন",
    "forgot_password": "পাসওয়ার্ড ভুলে গেছেন?",
    "login_button": "লগইন করুন",
    "or": "অথবা",
    "google_login": "গুগল দিয়ে লগইন করুন",
    "session_logout_desc": "আপনার সেশন শেষ করুন",
    "username_not_found": "এই ইউজারনেমটি পাওয়া যায়নি।",
    "cart_empty": "আপনার কার্ট খালি",
    "cart_empty_desc": "পছন্দসই পণ্য যোগ করতে শপে যান",
    "proceed_to_checkout": "অর্ডার সম্পন্ন করুন",
    "shipping_calc_checkout": "ডেলিভারি চার্জ চেকআউট পেজে যোগ করা হবে",
    "inside_dhaka": "ঢাকা সিটির ভেতরে",
    "inside_ctg": "চট্টগ্রাম সিটির ভেতরে",
    "outside_dhaka_ctg": "ঢাকা এবং চট্টগ্রাম সিটির বাহিরে",
    "fill_all_fields": "সবগুলো ঘর সঠিকভাবে পূরণ করুন।",
    "order_success_msg": "আমরা শীঘ্রই আপনার সাথে যোগাযোগ করব।",
    "full_name_label": "নাম",
    "phone_number_label": "ফোন নম্বর",
    "address_label": "ঠিকানা",
    "delivery_area": "ডেলিভারি এরিয়া",
    "free": "ফ্রি",
    "total_payment": "মোট পেমেন্ট",
    "confirm_order": "অর্ডার কনফার্ম করুন",
    "order_placed_success": "অর্ডার সফলভাবে সম্পন্ন হয়েছে!",
    "thank_you": "ধন্যবাদ! 🎉",
    "order_received": "আপনার অর্ডারটি সফলভাবে গ্রহণ করা হয়েছে।",
    "rep_contact": "আমাদের প্রতিনিধি শীঘ্রই আপনার সাথে যোগাযোগ করবেন। আপনার দিনটি শুভ হোক!",
    "cod_info": "ক্যাশ অন ডেলিভারিতে অর্ডার করতে তথ্য দিন",
    "delivery_info": "ডেলিভারি তথ্য",
    "your_name_placeholder": "আপনার নাম লিখুন",
    "address_placeholder": "আপনার পূর্ণ ঠিকানা লিখুন (বাসা/রোড/থানা/জেলা)",
    "shipping_area": "শিপিং এলাকা",
    "coupon_placeholder": "কুপন কোড (যদি থাকে)",
    "apply": "এপ্লাই",
    "order_note": "অর্ডার নোট (ঐচ্ছিক)",
    "order_note_placeholder": "বিশেষ কোনো নির্দেশনা থাকলে লিখুন...",
    "data_safe": "আপনার তথ্য আমাদের কাছে নিরাপদ",
    "need_help_whatsapp": "সহযোগিতা প্রয়োজন? হোয়াটসঅ্যাপে কথা বলুন",
    "incomplete": "ইনকমপ্লিট",
    "items_count": "টি পণ্য",
    "delivery_charge": "ডেলিভারি চার্জ",
    "add": "যোগ করুন",
    "all_products": "সকল প্রোডাক্ট",
    "shop_desc": "আপনার ঘরকে ইসলামিক ও সুন্দর করতে আমাদের প্রিমিয়াম কালেকশন থেকে বেছে নিন",
    "total_products_found": "টি প্রোডাক্ট পাওয়া গেছে",
    "sort_by": "সর্ট করুন",
    "most_popular": "সর্বাধিক জনপ্রিয়",
    "new_arrivals": "নতুন কালেকশন",
    "price_low_high": "মূল্য: কম → বেশি",
    "price_high_low": "মূল্য: বেশি → কম",
    "popular_search": "জনপ্রিয় সার্চ:",
    "filter": "ফিল্টার করুন",
    "price_range": "দামের পরিসর",
    "suitable_for": "সাজানোর জন্য উপযুক্ত",
    "reset_filters": "ফিল্টার রিসেট করুন",
    "loading_products": "লোড হচ্ছে...",
    "apply_filters": "প্রয়োগ করুন",
    "reset_all": "সব রিসেট করুন",
    "color": "কালার",
    "size": "সাইজ",
    "loading_excellence": "লোড হচ্ছে...",
    "product_not_found": "পণ্যটি পাওয়া যায়নি",
    "product_not_found_desc": "আপনি যে পণ্যটি খুঁজছেন তা বিদ্যমান নেই বা সরানো হয়েছে।",
    "back_to_shop": "শপে ফিরে যান",
    "best_seller": "বেস্ট সেলার",
    "reviews_count": "রিভিউ",
    "premium_quality_badge": "প্রিমিয়াম কোয়ালিটি",
    "product_code": "পণ্য কোড",
    "save_amount": "আপনি সেভ করছেন",
    "frame": "ফ্রেম",
    "quantity": "পরিমাণ",
    "product_details": "পণ্যের বিবরণ",
    "product_type": "পণ্যের ধরন",
    "material": "উপাদান",
    "installation": "ইনস্টলেশন",
    "description": "বিবরণ",
    "whats_in_box": "প্যাকেজে যা থাকছে",
    "related_products": "সম্পর্কিত পণ্য",
    "happy_customers_stat": "সন্তুষ্ট গ্রাহক",
    "google_rating": "গুগল রেটিং",
    "original_product_stat": "অরিজিনাল প্রোডাক্ট",
    "fast_delivery_stat": "দ্রুততম ডেলিভারি",
    "price_label": "মূল্য",
    "off": "ছাড়",
    "exclusive_savings": "এক্সক্লুসিভ সেভিংস ডিল",
    "our_ultimate": "আমাদের সেরা",
    "combo_offers_title": "কম্বো অফারসমূহ",
    "combo_desc": "আপনার প্রিয় ঘরকে সাজাতে আমাদের প্রিমিয়াম প্রোডাক্টগুলোর বিশেষ বান্ডেল কিনুন এবং সাশ্রয় করুন আকর্ষণীয় মূল্যে।",
    "all_filter": "সবগুলো",
    "hot_deal": "হট ডিল",
    "save": "সাভে করুন",
    "in_stock": "স্টকে আছে",
    "combo_price": "কম্বো প্রাইস",
    "details": "বিস্তারিত",
    "no_combos": "এখনই কোনো কম্বো অফার নেই",
    "no_combos_desc": "আমরা নতুন কিছু নিয়ে কাজ করছি। খুব শীঘ্রই দারুণ সব অফার আসছে।",
    "browse_all": "সব প্রোডাক্ট দেখুন",
    "limited_time": "সীমিত সময়ের অফার",
    "limited_time_desc": "নির্দিষ্ট সময়ের জন্য বিশেষ সাশ্রয়।",
    "premium_quality_stat": "প্রিমিয়াম কোয়ালিটি",
    "premium_quality_desc": "সর্বোচ্চ মানের নিশ্চিত গ্যারান্টি।",
    "lightning_delivery": "দ্রুত ডেলিভারি",
    "lightning_delivery_desc": "সারা দেশে দ্রুততম ডেলিভারি।",
    "incomplete_orders_title": "ইনকমপ্লিট অর্ডার ⚠️",
    "incomplete_orders_desc": '"যারা অর্ডার সম্পন্ন না করে চলে গেছে"',
    "total_incomplete": "মোট ইনকমপ্লিট",
    "refresh_data": "রিফ্রেশ ডাটা",
    "today_incomplete": "আজকের ইনকমপ্লিট",
    "abandoned_total": "অ্যাবান্ডন্ড (মোট)",
    "recovered_label": "রিকভার্ড",
    "recovery_rate": "রিকভারি রেট",
    "today": "আজ",
    "7_days": "৭ দিন",
    "30_days": "৩০ দিন",
    "search_incomplete_placeholder": "ফোন, নাম বা ইমেইল খুঁজুন...",
    "time": "সময়",
    "customer_label": "কাস্টমার",
    "product_label": "প্রোডাক্ট",
    "page_label": "পেজ",
    "contact_action": "কন্টাক্ট",
    "no_incomplete_msg": "কোন ইনকমপ্লিট অর্ডার নেই",
    "all_clear_msg": "সব ক্লিয়ার! ভালো ব্যবসা হচ্ছে। ✨",
    "convert_order_title": "অর্ডার কনভার্ট করুন",
    "customer_info_title": "কাস্টমার ইনফরমেশন",
    "payment_calc_title": "পেমেন্ট ক্যালকুলেশন",
    "selected_product_title": "সিলেক্টেড প্রোডাক্ট",
    "expert_tips_title": "এক্সপার্ট টিপস",
    "expert_tips_desc": '"অর্ডার কনভার্ট করার আগে কাস্টমারের ফোন নম্বর সঠিক কিনা যাচাই করে নিন। সঠিক কাস্টমার ডাটা ডেলিভারি সাকসেস রেট বাড়াতে সাহায্য করে।"',
    "confirm_order_btn": "কনফার্ম অর্ডার",
    "fraud_intel_title": "ফ্রড ইন্টেলিজেন্স ভেরিফিকেশন",
    "Main Menu": "মূল মেনু",
    "Dashboard": "ড্যাশবোর্ড",
    "Orders": "অর্ডার",
    "All Orders": "সকল অর্ডার",
    "Incomplete Orders": "ইনকমপ্লিট অর্ডার",
    "Products": "প্রোডাক্ট",
    "Combo Offers": "কম্বো অফার",
    "Categories": "ক্যাটাগরি",
    "Notifications": "নোটিফিকেশন",
    "Inventory": "ইনভেন্টরি",
    "Finance": "ফাইন্যান্স",
    "Visitor Tracking": "ভিজিটর ট্র্যাকিং",
    "Marketing": "মার্কেটিং",
    "Coupons": "কুপন",
    "Customers": "কাস্টমার",
    "Reviews": "রিভিউ",
    "Settings": "সেটিংস",
    "Team Management": "টিম ম্যানেজমেন্ট",
    "Team Members": "টিম মেম্বার",
    "Departments": "ডিপার্টমেন্ট",
    "Courier Management": "কুরিয়ার ম্যানেজমেন্ট",
    "Fraud Checker": "ফ্রড চেকার",
    "order_hub": "অর্ডার হাব",
    "low_success_redirect_url": "লো সাকসেস রিডাইরেক্ট URL",
    "blocking_filters": "ব্লকিং ফিল্টার",
    "block_zero_history": "জিরো হিস্টোরি ব্লক",
    "only_known_numbers": "শুধুমাত্র পরিচিত নম্বর অনুমোদন",
    "rapid_submission_filter": "দ্রুত সাবমিশন ফিল্টার",
    "prevent_rapid_orders": "দ্রুত পুনরাবৃত্তি অর্ডার প্রতিরোধ",
    "min_interval_seconds": "সর্বনিম্ন ইন্টারভাল (সেকেন্ড)",
    "frequency_limits": "ফ্রিকোয়েন্সি লিমিট",
    "device_limit": "ডিভাইস লিমিট",
    "browser_instance": "ব্রাউজার ইনস্ট্যান্স",
    "number_limit": "নম্বর লিমিট",
    "phone_identifier": "ফোন আইডেন্টিফায়ার",
    "ip_limit": "আইপি লিমিট",
    "network_address": "নেটওয়ার্ক এড্রেস",
    "block_duration_hrs": "ব্লক সময় (ঘন্টা)",
    "menu_visibility": "মেনু ভিজিবিলিটি",
    "control_header_desc": "হেডার এলিমেন্টগুলো নিয়ন্ত্রণ করুন",
    "all_categories_menu": "সকল ক্যাটাগরি মেনু",
    "show_category_dropdown_desc": "হেডারে ক্যাটাগরি ড্রপডাউন দেখান",
    "promo_badge_offer": "প্রোমো ব্যাজ (অফার)",
    "promo_badge_desc": "হেডারের ডানদিকের হাইলাইটেড বাটন",
    "enable_badge": "ব্যাজ সক্রিয় করুন",
    "header_menu_links": "হেডার মেনু লিঙ্ক",
    "organize_menu_desc": "মেনু আইটেমগুলো যোগ করুন এবং সাজান",
    "add_link": "নতুন লিঙ্ক",
    "no_links_msg": "এখনও কোনো লিঙ্ক যোগ করা হয়নি",
    "add_links_instruction": "আপনার সাইটের হেডার মেনুতে লিঙ্ক যোগ করুন",
    "enter_phone": "ফোন নম্বর দিন...",
    "searching_networks": "নেটওয়ার্কে খোঁজা হচ্ছে...",
    "courier_intelligence": "কুরিয়ার ইন্টেলিজেন্স",
    "recent_complaints": "সাম্প্রতিক অভিযোগ",
    "check_history": "হিস্ট্রি চেক করুন",
    "checking_7_networks": "৭+ ডেলিভারি নেটওয়ার্ক থেকে চেক করা হচ্ছে",
    "close": "বন্ধ করুন",
    "high_risk_customer": "উচ্চ ঝুঁকি সম্পন্ন কাস্টমার!",
    "low_success_rate": "ডেলিভারি সাকসেস রেট খুবই কম",
    "fraud_intelligence": "ফ্রড ইন্টেলিজেন্স",
    "full_intel": "বিস্তারিত",
    "Safe": "নিরাপদ",
    "Risk": "ঝুঁকি",
    "Caution": "সতর্কতা",
    "Safe Account": "নিরাপদ অ্যাকাউন্ট",
    "High Risk": "উচ্চ ঝুঁকি",
    "Caution Advised": "সতর্কতা প্রয়োজন",
    "new_alerts": "নতুন সতর্কবার্তা",
    "clear_all": "সব মুছুন",
    "new_order": "নতুন অর্ডার",
    "low_stock_alert": "লো স্টক অ্যালার্ট",
    "no_notifications": "কোনো নোটিফিকেশন নেই",
    "smooth_running": "সবকিছু ঠিকঠাক আছে",
    "dismiss": "মুছুন",
    "profile_saved": "প্রোফাইল সফলভাবে সেভ করা হয়েছে ✅",
    "profile_update_failed": "প্রোফাইল আপডেট করতে ব্যর্থ",
    "avatar_updated": "ছবি সফলভাবে আপলোড হয়েছে",
    "upload_failed": "আপলোড করতে ব্যর্থ হয়েছে",
    "passwords_mismatch": "পাসওয়ার্ড ম্যাচ করেনি",
    "password_changed": "পাসওয়ার্ড সফলভাবে পরিবর্তন করা হয়েছে 🔒",
    "member_since": "সদস্য হয়েছেন:",
    "personal_info": "ব্যক্তিগত তথ্য",
    "basic_profile_settings": "আপনার মৌলিক প্রোফাইল সেটিংস",
    "full_name": "পূর্ণ নাম",
    "username": "ব্যবহারকারীর নাম",
    "email": "ইমেইল",
    "phone_number": "ফোন নম্বর",
    "save_profile": "প্রোফাইল সেভ করুন",
    "access_security": "নিরাপত্তা",
    "update_access_credentials": "পাসওয়ার্ড পরিবর্তন করুন",
    "existing_key": "বর্তমান পাসওয়ার্ড",
    "new_secure_key": "নতুন পাসওয়ার্ড",
    "verify_new_key": "পাসওয়ার্ড নিশ্চিত করুন",
    "update_password": "পাসওয়ার্ড আপডেট করুন",
    "syncing_profile": "প্রোফাইল তথ্য সিঙ্ক হচ্ছে...",
    "verified_identity": "ভেরিফাইড প্রোফাইল",
    "active_node": "সক্রিয় অ্যাকাউন্ট",
    "super_admin": "সুপার অ্যাডমিন",
    "admin_role": "অ্যাডমিন",
    "moderator": "মডারেটর",
    "production": "প্রোডাকশন",
    "load_users_failed": "ইউজার লোড করতে ব্যর্থ",
    "updating_role": "রোল আপডেট হচ্ছে...",
    "role_updated": "রোল সফলভাবে আপডেট হয়েছে",
    "role_update_failed": "আপডেট করতে ব্যর্থ",
    "confirm_remove_user": "আপনি কি নিশ্চিতভাবে এই ইউজারকে রিমুভ করতে চান?",
    "user_removed": "ইউজার রিমুভ করা হয়েছে",
    "remove_user_failed": "রিমুভ করতে ব্যর্থ",
    "user_roles": "ইউজার রোলস",
    "active_administrators": "সক্রিয় প্রশাসক",
    "add_new_admin": "নতুন ইউজার",
    "super_admins": "সুপার অ্যাডমিন",
    "moderators": "মডারেটর",
    "system_health": "সিস্টেম হেলথ",
    "optimal": "সর্বোত্তম",
    "search_users_placeholder": "সার্চ ইউজার, রোল বা ইমেইল...",
    "user_table_user": "ইউজার",
    "access_role": "এক্সেস রোল",
    "last_active": "সর্বশেষ সক্রিয়",
    "actions": "আকশনসমূহ",
    "active": "সক্রিয়",
    "invite_admin": "অ্যাডমিন আমন্ত্রণ জানান",
    "access_management_hub": "এক্সেস ম্যানেজমেন্ট হাব",
    "user_email_address": "ইউজার ইমেইল অ্যাড্রেস",
    "permission_role": "পারমিশন রোল",
    "full_control": "সম্পূর্ণ নিয়ন্ত্রণ",
    "manage_data": "ডেটা পরিচালনা",
    "discard": "বাতিল করুন",
    "send_invitation": "আমন্ত্রণ পাঠান",
    "invitation_sent": "আমন্ত্রণ পাঠানো হয়েছে",
    "roles_permissions": "রোল ও পারমিশন",
    "roles_permissions_desc": "রোল তৈরি, সম্পাদনা করুন এবং পারমিশন পরিচালনা করুন",
    "search_roles_placeholder": "রোল খুঁজুন...",
    "add_new_role": "নতুন রোল যোগ করুন",
    "total_roles": "মোট রোল",
    "active_roles": "সক্রিয় রোল",
    "custom_roles": "কাস্টম রোল",
    "system_roles": "সিস্টেম রোল",
    "max_permission": "সর্বোচ্চ পারমিশন",
    "full_access": "সম্পূর্ণ অ্যাক্সেস",
    "min_permission": "সর্বনিম্ন পারমিশন",
    "limited_access": "সীমিত অ্যাক্সেস",
    "role_list": "রোল তালিকা",
    "members_count": "জন সদস্য",
    "system_role": "সিস্টেম রোল",
    "custom_role": "কাস্টম রোল",
    "permission_matrix": "পারমিশন ম্যাট্রিক্স",
    "selected_role": "সিলেক্টেড রোল:",
    "edit_role": "সম্পাদনা করুন",
    "module": "মডিউল",
    "view": "দেখুন",
    "delete": "মুছুন",
    "permission_note": "দ্রষ্টব্য: পারমিশন পরিবর্তন করলে সংশ্লিষ্ট রোলের সকল সদস্যদের ওপর প্রযোজ্য হবে।",
    "role_info": "রোলের তথ্য",
    "set_permissions": "পারমিশন সেট করুন",
    "review": "পর্যালোচনা",
    "name_desc": "নাম ও বিবরণ দিন",
    "select_modules": "মডিউল নির্বাচন করুন",
    "verify_details": "তথ্য যাচাই করুন",
    "role_name": "রোলের নাম",
    "role_name_placeholder": "যেমন: সাপোর্ট এজেন্ট",
    "role_slug": "রোল স্ল্যাগ (ইংরেজি)",
    "role_slug_placeholder": "যেমন: support_agent",
    "role_slug_desc": "সিস্টেম ব্যবহারের জন্য (ইংরেজি, ছোট হাতের অক্ষর ও আন্ডারস্কোর)",
    "role_desc": "রোলের বিবরণ",
    "role_desc_placeholder": "রোল সম্পর্কে সংক্ষিপ্ত বিবরণ দিন",
    "role_icon": "রোলের আইকন",
    "role_icon_desc": "রোলের জন্য একটি উপযুক্ত আইকন নির্বাচন করুন",
    "select_permissions_title": "পারমিশন নির্বাচন করুন",
    "select_permissions_desc": "এই রোলের জন্য কোন কোন মডিউলের কি অ্যাক্সেস থাকবে তা নির্বাচন করুন",
    "role_summary": "রোল সারসংক্ষেপ",
    "total_permissions": "মোট পারমিশন",
    "authorized": "টি অনুমোদিত",
    "primary_access": "প্রধান অ্যাক্সেস",
    "creator_auto": "সৃষ্টিকর্তা (স্বয়ংক্রিয়)",
    "created_date": "তৈরির তারিখ",
    "cancel": "বাতিল",
    "back": "পিছনে যান",
    "next_step": "পরবর্তী ধাপ",
    "save_role": "সংরক্ষণ করুন",
    "today_date": "আজ, ২৭ মে ২০২৩",
    "revoke_transaction": "লেনদেন বাতিল করুন",
    "verification_protocol": "ভেরিফিকেশন প্রোটোকল",
    "fraud_check_intelligence": "ফ্রড চেক ইন্টেলিজেন্স",
    "urgent_old": "জরুরি/পুরাতন",
    "medium": "মাধ্যম",
    "recent": "সাম্প্রতিক",
    "no_phone": "ফোন নম্বর নেই",
    "unknown_customer": "অজানা কাস্টমার",
    "manual_order_recovery": "ম্যানুয়াল অর্ডার রিকভারি",
    "manual_recovery_protocol": "ম্যানুয়াল রিকভারি প্রোটোকল",
    "real_time_security_check": "রিয়েল-টাইম সিকিউরিটি চেক",
    "ops_logistics": "অপারেশন ও লজিস্টিক্স",
    "ops_desc": "অর্ডার, শিপিং, ফ্রড",
    "growth_marketing": "গ্রোথ ও মার্কেটিং",
    "growth_desc": "ক্যাম্পেইন, CAPI, রিকভারি",
    "tech_infra": "টেকনিক্যাল ইনফ্রাস্ট্রাকচার",
    "infra_desc": "OTP, ফায়ারবেজ, নিরাপত্তা",
    "page_counter": "পেজ",
    "checkout_logic": "চেকআউট লজিক",
    "of": "এর মধ্যে",
    "logistics_desc": "প্রাইমারি শিপিং ইঞ্জিন কনফিগার করুন",
    "default_courier": "ডিফল্ট কুরিয়ার",
    "sandbox_mode": "স্যান্ডবক্স মোড",
    "sandbox_desc": "টেস্টিং এনভায়রনমেন্ট",
    "active_integrations": "সক্রিয় ইন্টিগ্রেশন",
    "integrations_desc": "শিপিং পার্টনার কানেকশন ম্যানেজ করুন",
    "add_provider": "নতুন যোগ করুন",
    "secure_engine": "সিকিউর ইঞ্জিন",
    "staging": "স্টেজিং",
    "disconnect_engine": "ইঞ্জিন ডিসকানেক্ট করুন",
    "fraud_detection": "ফ্রড ইন্টেলিজেন্স",
    "bd_courier_integration": "বিডি কুরিয়ার সলিউশন",
    "fetching_plan": "প্ল্যান রেজিস্ট্রি আনা হচ্ছে...",
    "active_plan": "সক্রিয় প্ল্যান",
    "signals_remaining": "সিগন্যাল বাকি আছে",
    "registry_usage": "রেজিস্ট্রি ব্যবহার",
    "total_hits": "মোট হিট",
    "invalid_key": "অকার্যকর রেজিস্ট্রি কি অথবা কোন প্ল্যান পাওয়া যায়নি",
    "neural_fraud": "নিউরন ফ্রড ডিটেকশন",
    "neural_desc": "১০ মিলিয়নের বেশি ডেলিভারি রেকর্ড স্ক্যান করে ফ্রড শনাক্তকরণ।",
    "upgrade_registry": "রেজিস্ট্রি আপগ্রেড করুন",
    "meta_capi": "মেটা কনভারশন API",
    "meta_capi_desc": "সার্ভার-সাইড ট্র্যাকিংয়ের মাধ্যমে ডাটা লস কমিয়ে আপনার মার্কেটিং পারফরম্যান্স বৃদ্ধি করুন।",
    "engine_control": "ইঞ্জিন কন্ট্রোল",
    "strict_validation": "স্ট্রিক্ট ট্র্যাকিং",
    "strict_validation_desc": "শুধুমাত্র কনফার্ম করা অর্ডারের ডাটা পাঠাবে। এতে ডাটার নির্ভুলতা শতভাগ নিশ্চিত হয়।",
    "high_precision": "হাই প্রিসিশন",
    "low_latency": "লো ল্যাটেন্সি",
    "api_credentials": "API ক্রেডেনশিয়াল",
    "auth_protocols": "অথোরাইজড এক্সেস প্রোটোকল",
    "token_expiry_hint": "সার্ভার-টু-সার্ভার এক্সেস টোকেন নির্দিষ্ট সময় পর পর এক্সপায়ার হতে পারে।",
    "email_alert": "ইমেইল অ্যালার্ট",
    "template_identifier": "টেমপ্লেট আইডেন্টিফায়ার",
    "delivered_desc": "পণ্য বুঝে পাওয়ার পর",
    "cancelled_desc": "অর্ডারটি ক্যানসেল করলে",
    "logic_active": "লজিক অ্যাক্টিভ",
    "logic_inactive": "লজিক ইনঅ্যাক্টিভ",
    "hero_master": "হিরো মাস্টার",
    "promo_hub": "প্রোমো হাব",
    "action_bar": "অ্যাকশন বার",
    "trust_panel": "ট্রাস্ট প্যানেল",
    "combo_suite": "কম্বো সুইট",
    "exclusive_collection": "এক্সক্লুসিভ কালেকশন",
    "new_arrival": "নিউ অ্যারাইভাল",
    "discover_premium": "আমাদের প্রিমিয়াম প্রোডাক্টগুলো দেখুন...",
    "edit_visuals": "ভিস্যুয়াল এডিট করুন",
    "slide_description": "স্লাইড ডেসক্রিপশন",
    "link_protocol": "লিংক প্রোটোকল",
    "upload_creative": "ক্রিয়েটিভ আপলোড করুন",
    "active_banners": "সক্রিয় ব্যানার",
    "init_banner": "ব্যানার শুরু করুন",
    "trust_badges_hub": "ট্রাস্ট ব্যাজ হাব",
    "badge_title": "ব্যাজ টাইটেল",
    "badge_subtitle": "ব্যাজ সাবটাইটেল",
    "header_elements_desc": "হেডার মেনুর এলিমেন্টগুলো নিয়ন্ত্রণ করুন",
    "show_cat_dropdown": "ড্রপডাউন মেনু প্রদর্শন করুন",
    "promo_anchor": "প্রোমো অ্যাঙ্কর",
    "header_highlight_desc": "হেডারে হাইলাইটেড প্রোমো টেক্সট",
    "anchor_text": "অ্যাঙ্কর টেক্সট",
    "anchor_link": "অ্যাঙ্কর লিংক",
    "link_orchestration": "লিংক অর্কেস্ট্রেশন",
    "navigation_matrix_desc": "স্টোরের মূল নেভিগেশন লিংকগুলো সাজান",
    "label_en": "লেবেল (English)",
    "label_bn": "লেবেল (Bangla)",
    "url_path": "URL পাথ",
    "new_link": "নতুন লিংক",
    "live_updates": "লাইভ আপডেট",
    // Team Management
    "team_management_desc": "টিমের সদস্যদের পরিচালনা করুন এবং তাদের কার্যক্রম তদারকি করুন",
    "invite_member": "আমন্ত্রণ জানান",
    "add_new_member": "নতুন সদস্য যোগ করুন",
    "total_members": "মোট সদস্য",
    "active_members": "সক্রিয় সদস্য",
    "invite_sent": "আমন্ত্রণ পাঠানো হয়েছে",
    "inactive_members": "নিষ্ক্রিয় সদস্য",
    "all_members": "সকল সদস্য",
    "search_staff_placeholder": "নাম, ইমেইল বা ফোন দিয়ে খুঁজুন...",
    "joining_date": "যোগদানের তারিখ",
    "view_edit": "দেখুন / সম্পাদনা",
    "delete_member": "সদস্য মুছুন",
    "staff_activity_log": "স্টাফ কার্যকলাপ লগ",
    "recent_modifications": "সাম্প্রতিক পরিবর্তনসমূহ",
    "export_csv": "CSV রপ্তানি",
    "no_activity": "কোনো কার্যকলাপ নেই",
    "email_address": "ইমেইল ঠিকানা",
    "confirm_password": "পাসওয়ার্ড নিশ্চিত করুন",
    "job_title": "পদবি",
    "select_department": "বিভাগ নির্বাচন করুন",
    "you": "আপনি",
    // Common UI labels
    "member": "সদস্য",
    "role": "ভূমিকা",
    "department": "বিভাগ",
    "inactive": "নিষ্ক্রিয়",
    "next": "পরবর্তী",
    "loading": "লোড হচ্ছে...",
    "required": "আবশ্যক",
    "optional": "ঐচ্ছিক",
    "yes": "হ্যাঁ",
    "no": "না",
    "confirm": "নিশ্চিত করুন",
    "success": "সফল",
    "error": "ত্রুটি",
    "name": "নাম",
    "phone": "ফোন",
    "amount": "পরিমাণ",
    "image": "ছবি",
    "submit": "জমা দিন",
    "update": "আপডেট করুঠন",
    "refresh": "রিফ্রেশ করুন",
    "import": "আমদানি",
    "download": "ডাউনলোড",
    "upload": "আপলোড",
    "profile": "প্রোফাইল",
    "login": "লগ ইন",
    "password": "পাসওয়ার্ড",
    "created_at": "তৈরির তারিখ",
    "updated_at": "আপডেটের তারিখ",
  },
  en: {
    "home": "Home",
    "lang": "en",
    "shop": "Shop",
    "combo": "Combo",
    "reviews": "Reviews",
    "combo_management": "Combo Management",
    "total_bundles_listed": "Total {count} bundles listed",
    "new_combo": "New Combo",
    "combo_info": "Combo Info",
    "product_count": "Products",
    "price_taka": "Price (৳)",
    "active_listings": "Active Listings",
    "stock_warnings": "Stock Warnings",
    "combo_revenue": "Combo Revenue",
    "cart": "Cart",
    "checkout": "Checkout",
    "buy_now": "Buy Now",
    "add_to_cart": "Add to Cart",
    "search": "Search",
    "contact": "Contact",
    "shipping_policy": "Shipping Policy",
    "return_policy": "Return Policy",
    "follow_us": "Follow Us",
    "company": "Company",
    "address": "Address",
    "all_categories": "All Categories",
    "quick_links": "Quick Links",
    "order_now": "Order Now",
    "free_shipping": "Free Shipping",
    "premium_quality": "Premium Quality",
    "customer_support": "Support",
    "view_details": "View Details",
    "out_of_stock": "Out of Stock",
    "subtotal": "Subtotal",
    "total": "Total",
    "tax": "Tax",
    "discount": "Discount",
    "shop_now": "Shop Now",
    "learn_more": "Learn More",
    "privacy_policy": "Privacy Policy",
    "terms_conditions": "Terms & Conditions",
    "satisfied_customers": "Satisfied Customers",
    "products_delivered": "Products Delivered",
    "fast_delivery": "Fast Nationwide Delivery",
    "original_products": "100% Original Products",
    "cash_on_delivery": "Cash on Delivery",
    "delivery_dhaka": "Fast Delivery in Dhaka",
    "damage_replace": "Damage Replace",
    "happy_customers": "Happy Customers",
    "see_details": "See Details",
    "my_account": "My Account",
    "shopping_cart": "Shopping Cart",
    "product_suggestions": "Product Suggestions",
    "searching": "Searching...",
    "no_products_found": "No products found",
    "failed_to_load_dashboard_data": "Failed to load dashboard data",
    "super_admin_label": "Super Admin",
    "admin_label": "Admin",
    "moderator_label": "Moderator",
    "production_label": "Production",
    "confirm_delete": "Are you sure you want to delete this?",
    "delete_success": "Deleted successfully",
    "total_inventory": "Total Inventory",
    "total_payable": "Total Payable",
    "on_hold": "On Hold",
    "select_items": "Select items",
    "update_failure": "Update failure",
    "product_deleted_success": "Product deleted successfully",
    "settings_load_failed": "Failed to load settings",
    "saving_changes": "Saving changes...",
    "settings_save_success": "Settings saved successfully",
    "settings_save_failed": "Failed to save settings",
    "save_changes": "Save Changes",
    "upload_success": "Upload success",
    "hero_section": "Hero Section",
    "banner_slides": "Banner Slides",
    "slide": "Slide",
    "badge_text": "Badge Text",
    "title": "Title",
    "sub_text": "Sub Text",
    "btn1_text": "Button 1 Text",
    "btn2_text": "Button 2 Text",
    "image_url": "Image URL",
    "layout": "Layout",
    "left": "Left",
    "right": "Right",
    "add_slide": "Add Slide",
    "hero_text_customization": "Hero Text Customization",
    "trust_badges": "Trust Badges",
    "credibility_indicators": "Credibility Indicators",
    "add_badge": "Add Badge",
    "categories": "Categories",
    "category_section": "Category Section",
    "show_categories": "Show Categories",
    "display_on_homepage": "Display on Homepage",
    "featured_products": "Featured Products",
    "highlighted_products": "Highlighted Products",
    "show_featured": "Show Featured",
    "special_products_highlight": "Special Products Highlight",
    "combo_section": "Combo Section",
    "combo_offers": "Combo Offers",
    "show_combo": "Show Combo",
    "display_combo_offers": "Display Combo Offers",
    "why_choose_us": "Why Choose Us",
    "benefits": "Benefits",
    "photo_gallery": "Photo Gallery",
    "customer_photos": "Customer Photos",
    "customer_feedback": "Customer Feedback",
    "islamic_quote": "Islamic Quote",
    "wisdom_text": "Wisdom Text",
    "cta_banner": "CTA Banner",
    "bottom_banner": "Bottom Banner",
    "view_all_results": "View All Results",
    "search_placeholder": "Search for products...",
    "decor_dream_space": "Decor Your Dream Space",
    "packing_operations": "Packing Operations",
    "orders_ready": "Orders Ready",
    "start_packing": "Start Packing",
    "verification_queue": "Verification Queue",
    "pending_orders": "Pending Orders",
    "verify_orders": "Verify Orders",
    "recent_orders": "Recent Orders",
    "latest_orders": "Latest Orders",
    "view_all": "View All",
    "order": "Order",
    "customer": "Customer",
    "date": "Date",
    "total_label": "Total",
    "status": "Status",
    "pending": "Pending",
    "confirmed": "Confirmed",
    "processing": "Processing",
    "shipped": "Shipped",
    "delivered": "Delivered",
    "cancelled": "Cancelled",
    "returned": "Return",
    "today_orders": "Today's Orders",
    "today_revenue": "Today's Revenue",
    "total_revenue": "Total Revenue",
    "monthly_revenue": "Monthly Revenue",
    "total_products": "Total Products",
    "out_of_stock_kpi": "Out of Stock",
    "courier_balance": "Courier Balance",
    "live": "Live",
    "sales_graph": "Sales Graph",
    "revenue_trend": "Revenue Trend",
    "days": "Days",
    "order_status": "Order Status",
    "distribution": "Distribution",
    "order_summary": "Order Summary",
    "all_statuses": "All Statuses",
    "top_selling": "Top Selling",
    "best_products": "Best Products",
    "no_data": "No data",
    "sold": "Sold",
    "morning": "Good Morning",
    "afternoon": "Good Afternoon",
    "evening": "Good Evening",
    "footer_desc_fallback": "Combining premium quality with modern design to make your lifestyle more beautiful and easy.",
    "dhaka_bangladesh": "Dhaka, Bangladesh",
    "categories_title": "Categories",
    "settings_title": "Settings",
    "helpline": "Helpline",
    "whatsapp_chat": "WhatsApp Chat",
    "secure_checkout": "100% Secure Checkout",
    "order_success_msg": "We will contact you shortly to confirm.",
    "full_name_label": "Full Name",
    "phone_number_label": "Phone Number",
    "address_label": "Address",
    "delivery_area": "Delivery Area",
    "free": "Free",
    "total_payment": "Total Payment",
    "confirm_order": "Confirm Order",
    "order_placed_success": "Order Placed Successfully!",
    "thank_you": "Thank You! 🎉",
    "order_received": "Your order has been successfully placed.",
    "rep_contact": "Our representative will contact you soon. Have a great day!",
    "cod_info": "Provide details to order via Cash on Delivery",
    "delivery_info": "Delivery Info",
    "your_name_placeholder": "Enter your name",
    "address_placeholder": "Enter full address (House/Road/Police Station/District)",
    "shipping_area": "Shipping Area",
    "coupon_placeholder": "Coupon Code (if any)",
    "apply": "Apply",
    "order_note": "Order Note (Optional)",
    "order_note_placeholder": "Special instructions (if any)...",
    "data_safe": "Your data is safe with us",
    "need_help_whatsapp": "Need help? Chat on WhatsApp",
    "incomplete": "Incomplete",
    "items_count": "Items",
    "delivery_charge": "Delivery Charge",
    "add": "Add",
    "all_products": "All Products",
    "shop_desc": "Choose from our premium collection to make your home Islamic and beautiful",
    "total_products_found": "products found",
    "sort_by": "Sort By",
    "most_popular": "Most Popular",
    "new_arrivals": "New Arrivals",
    "price_low_high": "Price: Low to High",
    "price_high_low": "Price: High to Low",
    "popular_search": "Popular Search:",
    "filter": "Filter",
    "price_range": "Price Range",
    "suitable_for": "Suitable For",
    "reset_filters": "Reset Filters",
    "loading_products": "Loading products...",
    "apply_filters": "Apply Filters",
    "reset_all": "Reset All",
    "color": "Color",
    "size": "Size",
    "loading_excellence": "Loading Excellence...",
    "product_not_found": "Product Not Found",
    "product_not_found_desc": "The product you are looking for doesn't exist or has been moved.",
    "back_to_shop": "Back to shop",
    "best_seller": "Best Seller",
    "reviews_count": "Reviews",
    "premium_quality_badge": "Premium Quality",
    "product_code": "Product Code",
    "save_amount": "You Save",
    "frame": "Frame",
    "quantity": "Quantity",
    "product_details": "Product Details",
    "product_type": "Product Type",
    "material": "Material",
    "installation": "Installation",
    "description": "Description",
    "whats_in_box": "What's in the Box",
    "related_products": "Related Products",
    "happy_customers_stat": "Happy Customers",
    "google_rating": "Google Rating",
    "original_product_stat": "Original Product",
    "fast_delivery_stat": "Fastest Delivery",
    "price_label": "Price",
    "off": "Off",
    "exclusive_savings": "Exclusive Savings Deals",
    "our_ultimate": "Our Ultimate",
    "combo_offers_title": "Combo Offers",
    "combo_desc": "Transform your home with our specially curated premium bundles. High quality, beautiful designs, and massive savings.",
    "all_filter": "All",
    "hot_deal": "Hot Deal",
    "save": "SAVE",
    "in_stock": "In Stock",
    "combo_price": "Combo Price",
    "details": "Details",
    "no_combos": "No active combo offers",
    "no_combos_desc": "We're working on something special. Check back soon for amazing new deals!",
    "browse_all": "Browse All Products",
    "limited_time": "Limited Time Deals",
    "limited_time_desc": "Special savings for a limited period only.",
    "premium_quality_stat": "Premium Quality",
    "premium_quality_desc": "Guaranteed highest quality products.",
    "lightning_delivery": "Lightning Delivery",
    "lightning_delivery_desc": "Fastest delivery across the country.",
    "incomplete_orders_title": "Incomplete Orders ⚠️",
    "incomplete_orders_desc": '"Those who left without completing their order"',
    "total_incomplete": "Total Incomplete",
    "refresh_data": "Refresh Data",
    "today_incomplete": "Today's Incomplete",
    "abandoned_total": "Abandoned (Total)",
    "recovered_label": "Recovered",
    "recovery_rate": "Recovery Rate",
    "all": "All",
    "today": "Today",
    "7_days": "7 Days",
    "30_days": "30 Days",
    "search_incomplete_placeholder": "Search phone, name or email...",
    "time": "Time",
    "customer_label": "Customer",
    "product_label": "Product",
    "page_label": "Page",
    "action": "Action",
    "contact_action": "Contact",
    "no_incomplete_msg": "No Incomplete Orders",
    "all_clear_msg": "All clear! Business is booming. ✨",
    "convert_order_title": "Convert Order",
    "customer_info_title": "Customer Information",
    "payment_calc_title": "Payment Calculation",
    "selected_product_title": "Selected Products",
    "expert_tips_title": "Expert Tips",
    "expert_tips_desc": '"Verify the customer\'s phone number before converting. Accurate data helps increase delivery success rates."',
    "confirm_order_btn": "Confirm Order",
    "cancel_btn": "Cancel",
    "fraud_intel_title": "Fraud Intelligence Verification",
    "enter_phone": "Enter phone number...",
    "searching_networks": "Searching networks...",
    "courier_center": "Courier Center",
    "recent_complaints": "Recent Carrier Reports",
    "check_history": "Verify History",
    "checking_7_networks": "Checking records from 7+ delivery networks",
    "close": "Close",
    "high_risk_customer": "CRITICAL RISK",
    "low_success_rate": "EXTREMELY LOW SUCCESS RATE",
    "fraud_intelligence": "Fraud Intelligence",
    "full_intel": "Full Intel",
    "Safe": "Safe",
    "Risk": "Risk",
    "Caution": "Caution",
    "Safe Account": "Safe Account",
    "High Risk": "High Risk",
    "Caution Advised": "Caution Advised",
    "notifications": "Notifications",
    "new_alerts": "New Alerts",
    "clear_all": "Clear All",
    "new_order": "New Order",
    "low_stock_alert": "Low Stock Alert",
    "no_notifications": "No Notifications Yet",
    "smooth_running": "Everything is running smoothly",
    "dismiss": "Dismiss",
    "profile_saved": "Profile saved successfully ✅",
    "profile_update_failed": "Failed to update profile",
    "avatar_updated": "Avatar updated successfully",
    "upload_failed": "Upload failed",
    "passwords_mismatch": "Passwords do not match",
    "password_changed": "Password changed successfully 🔒",
    "member_since": "MEMBER SINCE:",
    "personal_info": "Personal Info",
    "basic_profile_settings": "Basic profile configurations",
    "full_name": "Full Name",
    "username": "Username",
    "email": "Email",
    "phone_number": "Phone Number",
    "save_profile": "Save Profile Configuration",
    "access_security": "Access Security",
    "update_access_credentials": "Update access credentials",
    "existing_key": "Existing Key",
    "new_secure_key": "New Secure Key",
    "verify_new_key": "Verify New Key",
    "update_password": "Encrypt & Update Access",
    "syncing_profile": "Synchronizing Profile Data...",
    "verified_identity": "Verified Identity",
    "active_node": "Active Node",
    "super_admin": "Super Admin",
    "admin_role": "Admin",
    "moderator": "Moderator",
    "production": "Production",
    "load_users_failed": "Failed to load users",
    "updating_role": "Updating role...",
    "role_updated": "Role updated successfully",
    "role_update_failed": "Failed to update role",
    "confirm_remove_user": "Are you sure you want to remove this user?",
    "user_removed": "User removed successfully",
    "remove_user_failed": "Failed to remove user",
    "user_roles": "User Roles",
    "active_administrators": "Active Administrators",
    "add_new_admin": "Add New Admin",
    "super_admins": "Super Admins",
    "moderators": "Moderators",
    "system_health": "System Health",
    "optimal": "Optimal",
    "search_users_placeholder": "Search user, role or email...",
    "user_table_user": "User",
    "access_role": "Access Role",
    "last_active": "Last Active",
    "actions": "Actions",
    "active": "Active",
    "invite_admin": "Invite Admin",
    "access_management_hub": "Access Management Hub",
    "user_email_address": "User Email Address",
    "permission_role": "Permission Role",
    "full_control": "Full Control",
    "manage_data": "Manage Data",
    "discard": "Discard",
    "send_invitation": "Send Invitation",
    "invitation_sent": "Invitation sent successfully",
    "roles_permissions": "Roles & Permissions",
    "roles_permissions_desc": "Create, edit and manage role-based access control",
    "search_roles_placeholder": "Search roles...",
    "add_new_role": "Add New Role",
    "total_roles": "Total Roles",
    "active_roles": "Active Roles",
    "custom_roles": "Custom Roles",
    "system_roles": "System Roles",
    "max_permission": "Max Permission",
    "full_access": "Full Access",
    "min_permission": "Min Permission",
    "limited_access": "Limited Access",
    "role_list": "Role List",
    "members_count": "Members",
    "system_role": "System Role",
    "custom_role": "Custom Role",
    "permission_matrix": "Permission Matrix",
    "selected_role": "Selected Role:",
    "edit_role": "Edit Role",
    "module": "Module",
    "view": "View",
    "edit": "Edit",
    "delete": "Delete",
    "export": "Export",
    "permission_note": "Super Admin permissions cannot be modified. It is a system default role.",
    "role_info": "Role Information",
    "set_permissions": "Set Permissions",
    "review": "Review",
    "name_desc": "Name & Description",
    "select_modules": "Select Modules",
    "verify_details": "Verify Details",
    "role_name": "Role Name",
    "role_name_placeholder": "e.g. Sales Manager",
    "role_slug": "Role Slug",
    "role_slug_placeholder": "e.g. sales_manager",
    "role_slug_desc": "System identifier (English & underscore only)",
    "role_desc": "Role Description",
    "role_desc_placeholder": "Describe role responsibilities...",
    "role_icon": "Role Icon",
    "role_icon_desc": "Choose an icon for the list view",
    "select_permissions_title": "Select Permissions",
    "select_permissions_desc": "Set access level per module",
    "role_summary": "Role Summary",
    "total_permissions": "Total Permissions",
    "authorized": "Authorized",
    "primary_access": "Primary Access",
    "creator_auto": "Created By",
    "created_date": "Created Date",
    "cancel": "Cancel",
    "back": "Back",
    "next_step": "Next Step",
    "save_role": "Save Role",
    "today_date": "Today",
    "Main Menu": "Main Menu",
    "Dashboard": "Dashboard",
    "Orders": "Orders",
    "All Orders": "All Orders",
    "Incomplete Orders": "Incomplete Orders",
    "Products": "Products",
    "Combo Offers": "Combo Offers",
    "Categories": "Categories",
    "Notifications": "Notifications",
    "Inventory": "Inventory",
    "Finance": "Finance",
    "Visitor Tracking": "Visitor Tracking",
    "Marketing": "Marketing",
    "Coupons": "Coupons",
    "Customers": "Customers",
    "Reviews": "Reviews",
    "Settings": "Settings",
    "Team Management": "Team Management",
    "Team Members": "Team Members",
    "Departments": "Departments",
    "Courier Management": "Courier Management",
    "Fraud Checker": "Fraud Checker",
    "login_welcome": "Welcome back!",
    "admin_panel": "Admin Panel",
    "fraud_prevention_system": "Fraud Prevention System",
    "fraud_prevention_desc": "These filters help block fraudulent orders. Configure carefully.",
    "success_rate_filters": "Success Rate Filters",
    "delivery_success_filter": "Delivery Success Filter",
    "verify_courier_history": "Verify courier delivery history",
    "min_success_rate": "Minimum Success Rate (%)",
    "low_success_redirect_url": "Low Success Redirect URL",
    "blocking_filters": "Blocking Filters",
    "block_zero_history": "Block Zero History",
    "only_known_numbers": "Only allow known numbers",
    "rapid_submission_filter": "Rapid Submission Filter",
    "prevent_rapid_orders": "Prevent rapid repeated orders",
    "min_interval_seconds": "Min Interval (seconds)",
    "frequency_limits": "Frequency Limits",
    "device_limit": "Device Limit",
    "browser_instance": "Browser instance",
    "number_limit": "Number Limit",
    "phone_identifier": "Phone identifier",
    "ip_limit": "IP Limit",
    "network_address": "Network address",
    "block_duration_hrs": "Block Duration (hrs)",
    "menu_visibility": "Menu Visibility",
    "control_header_desc": "Control header elements",
    "all_categories_menu": "All Categories Menu",
    "show_category_dropdown_desc": "Show category dropdown in header",
    "promo_badge_offer": "Promo Badge (Offer)",
    "promo_badge_desc": "Highlighted button on header right",
    "enable_badge": "Enable Badge",
    "header_menu_links": "Header Menu Links",
    "organize_menu_desc": "Add and organize menu items",
    "add_link": "Add Link",
    "no_links_msg": "No links added yet",
    "add_links_instruction": "Add links to your site header menu",
    "checkout_shipping_area": "Shipping Area",
    "checkout_complete_order": "Complete Order",
    "feature_control_title": "Full Control",
    "feature_control_desc": "Manage every aspect of your store with ease.",
    "password_placeholder": "••••••••",
    "remember_me": "Remember me",
    "forgot_password": "Forgot password?",
    "login_button": "Login Now",
    "or": "OR",
    "google_login": "Login with Google",
    "copyright": "All rights reserved.",
    "logout": "Logout",
    "session_logout_desc": "Terminate your session",
    "system_status": "System Status",
    "all_services_active": "All Services Active",
    "access_denied": "Access Denied",
    "access_denied_desc": "You do not have sufficient permissions to view this page. Please contact the Super Admin.",
    "return_to_dashboard": "Return to Dashboard",
    "main_menu": "Main Menu",
    "dashboard": "Dashboard",
    "orders": "Orders",
    "all_orders": "All Orders",
    "incomplete_orders": "Incomplete Orders",
    "products": "Products",
    "inventory": "Inventory",
    "finance": "Finance",
    "visitor_tracking": "Visitor Tracking",
    "marketing_customers": "Marketing & Customers",
    "marketing": "Marketing",
    "coupons": "Coupons",
    "customers": "Customers",
    "system_settings": "System & Settings",
    "team_management": "Team Management",
    "team_members": "Team Members",
    "departments": "Departments",
    "courier_management": "Courier Management",
    "fraud_checker": "Fraud Checker",
    "order_management": "Order Management",
    "live_transaction_stream": "Live Transaction Stream",
    "dispatch": "Dispatch",
    "search_orders": "Search orders...",
    "all_payments": "All Payments",
    "cod": "COD",
    "bkash": "bKash",
    "selected": "Selected",
    "bulk_actions": "Bulk Actions",
    "confirm_selected": "Confirm Selected",
    "processing_selected": "Processing Selected",
    "delete_selected": "Delete Selected",
    "print": "Print",
    "pack_order": "Pack Order",
    "send_to_courier": "Send to Courier",
    "select_courier": "Select Courier:",
    "book_now": "Book Now",
    "track": "Track",
    "ship_order": "Ship Order",
    "recover": "Recover",
    "invoice": "Invoice",
    "call": "Call",
    "order_details": "Order Details",
    "items_manifest": "Items Manifest",
    "units": "Units",
    "operational_timeline": "Operational Timeline",
    "active_stage": "Active Stage",
    "identity_profile": "Identity Profile",
    "logistics_hub": "Logistics Hub",
    "destination_address": "Destination Address",
    "view_on_satellite": "View on Satellite",
    "financial_settlement": "Financial Settlement",
    "freight": "Freight",
    "total_settlement": "Total Settlement",
    "internal_operational_logs": "Internal Operational Logs",
    "system_log_entry": "System log entry...",
    "abort_view": "Close",
    "authorize_order": "Approve Order",
    "terminate_order": "Cancel Order",
    "failed_load_orders": "Failed to load orders",
    "updating_orders": "Updating orders...",
    "orders_updated": "orders updated",
    "bulk_update_failure": "Bulk update failure",
    "confirm_bulk_delete": "Permanently delete selected orders?",
    "deleting_orders": "Deleting orders...",
    "orders_deleted": "Orders deleted",
    "delete_failure": "Delete failure",
    "manager_role_required": "Managerial role required",
    "order_status_success": "Order status updated successfully",
    "order_update_success": "Order updated successfully",
    "delete_order_confirm": "Do you want to delete this order permanently?",
    "order_deleted_success": "Order has been deleted",
    "delete_failed": "Could not delete order",
    "order_recovered_success": "Order has been recovered",
    "booking_to_courier": "is being booked to...",
    "booking_success": "Success! Tracking:",
    "booking_failed": "Booking failed",
    "verification_protocol_desc": "Verification Protocol Alpha",
    "note_optional": "Note (Optional)",
    "hold": "Hold",
    "void_security_protocol": "Cancel Order",
    "revocation_justification": "Reason for Cancellation",
    "abort_request": "Abort",
    "void_transaction": "Cancel Transaction",
    "courier_dispatch_center": "Courier Dispatch Center",
    "operational_gateway": "Courier Gateway",
    "operational_manifest": "Order List",
    "transmit_to_gateway": "Send All to Courier",
    "order_ready_count": "Orders Ready",
    "dispatching_to": "Dispatching to",
    "dispatch_success": "Successfully dispatched",
    "bulk_dispatch_failed": "Bulk dispatch failed",
    "terminate_order_confirm_pre": "Are you sure you want to",
    "permanently_decommission": "permanently delete",
    "revocation_justification_placeholder": "State operational reason for voiding...",
    "dispatch_warning_pre": "Initiating dispatch will transmit all",
    "dispatch_warning_mid": "orders to the",
    "dispatch_warning_post": "gateway for fulfillment. Ensure all customer data is validated before transmission.",
    "product_management": "Product Management",
    "total_products_live": "Managing {count} live products",
    "new_product": "New Product",
    "total_items": "Total Inventory",
    "draft_archived": "Draft / Archived",
    "search_catalog": "Search catalog...",
    "add_new_product": "Add New Product",
    "product_details_desc": "Provide your product details",
    "product_images": "Product Images",
    "ratio_hint": "Use 1:1 ratio images for best results",
    "upload_image": "Upload Image",
    "drag_drop_hint": "or drag and drop here",
    "primary_image": "Primary",
    "product_info": "Product Info",
    "product_name": "Product Name",
    "brand_optional": "Brand (Optional)",
    "model_sku_optional": "Model / SKU (Optional)",
    "short_description": "Short Description",
    "detailed_description": "Detailed Description",
    "pricing": "Pricing",
    "old_price_optional": "Old Price (Optional)",
    "discount_percentage": "Discount (%)",
    "stock_inventory": "Stock & Inventory",
    "stock_amount": "Stock Amount",
    "alert_level": "Alert Level",
    "hide_out_of_stock_hint": "Hide when out of stock",
    "product_attributes": "Product Attributes",
    "size_optional": "Size (Optional)",
    "color_optional": "Color (Optional)",
    "weight_optional": "Weight (Optional)",
    "add_more_attributes": "Add more attributes",
    "product_tags_optional": "Product Tags (Optional)",
    "tag_hint": "e.g. Islamic, Canvas, Wall Art",
    "landing_page_customization": "Landing Page Customization",
    "top_banner_text_label": "Top Banner Text",
    "whats_included_combo": "What's Included in Combo",
    "package_contents_sidebar": "Package Contents (Sidebar List)",
    "save_product": "Save Product",
    "product_saved_success": "Product saved successfully",
    "product_delete_confirm": "Are you absolutely certain you want to delete this product?",
    "status_active_success": "Listing activated",
    "status_inactive_success": "Listing deactivated",
    "type": "Type",
    "sku": "SKU",
    "view_on_store": "View on Store",
    "failed_load_products": "Failed to load products",
    "failed_load_categories": "Failed to load categories",
    "images_uploaded_success": "images uploaded successfully",
    "save_failure": "Save failure",
    "product_name_placeholder": "Enter product name",
    "brand_placeholder": "Enter brand",
    "sku_placeholder": "Enter SKU or Model number",
    "short_description_placeholder": "Enter short description (max 200 chars)",
    "tags_placeholder": "Enter tags and press Enter",
    "top_banner_placeholder": "e.g. Ramadan Offer! 40% Off",
    "add_line": "Add Line",
    "add_item": "Add Item",
    "team_management_desc": "Manage your team members and oversee their operational activities",
    "invite_member": "Invite Member",
    "add_new_member": "Add New Member",
    "total_members": "Total Members",
    "active_members": "Active Members",
    "invite_sent": "Invite Sent",
    "inactive_members": "Inactive Members",
    "inactive": "Inactive",
    "all_members": "All Members",
    "search_staff_placeholder": "Search by name, email or phone...",
    "member": "Member",
    "role": "Role",
    "department": "Department",
    "joining_date": "Joining Date",
    "you": "You",
    "view_edit": "View & Edit",
    "delete_member": "Delete Member",
    "staff_activity_log": "Staff Activity Log",
    "recent_modifications": "Recent system modifications ledger",
    "export_csv": "Export CSV",
    "no_activity": "No activity detected in system ledger",
    "email_address": "Email Address",
    "mobile_number": "Mobile Number",
    "password": "Password",
    "confirm_password": "Confirm Password",
    "job_title": "Job Title",
    "select_department": "Select Department",
    "additional_info": "Additional Info (Optional)",
    "description_placeholder": "Write detailed description...",
    "username_not_found": "Username not found.",
    "order_hub": "Order Hub",
    "revoke_transaction": "Revoke Transaction",
    "verification_protocol": "Verification Protocol",
    "fraud_check_intelligence": "Fraud Check Intelligence",
    "urgent_old": "Urgent/Old",
    "medium": "Medium",
    "recent": "Recent",
    "no_phone": "No Phone",
    "unknown_customer": "Unknown Customer",
    "manual_order_recovery": "Manual Order Recovery",
    "manual_recovery_protocol": "Manual Recovery Protocol Alpha-7",
    "real_time_security_check": "Real-time network security check",
    "inside_dhaka": "Inside Dhaka City",
    "inside_ctg": "Inside Chattogram City",
    "outside_dhaka_ctg": "Outside Dhaka & Chattogram",
    "proceed_to_checkout": "Complete Order",
    "fill_all_fields": "Please fill all required fields correctly.",
    "ops_logistics": "Operations & Logistics",
    "ops_desc": "Orders, Shipping, Fraud",
    "growth_marketing": "Growth & Marketing",
    "growth_desc": "Campaigns, CAPI, Recovery",
    "tech_infra": "Technical Infrastructure",
    "infra_desc": "OTP, Firebase, Security",
    "page_counter": "Page",
    "checkout_logic": "Checkout Logic",
    "page": "Page",
    "of": "of",
    "auto_confirmation": "Auto Confirmation",
    "auto_confirmation_desc": "For high success rate customers",
    "operational_security": "Operational Security",
    "external_links_tracking": "External Links & Tracking",
    "tracking_page_url": "Tracking Page URL",
    "terms_conditions_url": "Terms & Conditions URL",
    "logistics_desc": "Configure primary shipping engines",
    "default_courier": "Default Courier",
    "sandbox_mode": "Sandbox Mode",
    "sandbox_desc": "Testing Environment",
    "active_integrations": "Active Integrations",
    "integrations_desc": "Manage shipping partner connections",
    "add_provider": "Add Provider",
    "secure_engine": "Secure Engine",
    "staging": "Staging",
    "disconnect_engine": "Disconnect Engine",
    "bd_courier_integration": "BD Courier Integration",
    "fetching_plan": "Fetching Plan Registry...",
    "active_plan": "Active Plan",
    "signals_remaining": "Signals Remaining",
    "registry_usage": "Registry Usage",
    "total_hits": "Total Hits",
    "invalid_key": "Invalid Registry Key or No Plan Found",
    "neural_fraud": "Neural Fraud Detection",
    "neural_desc": "AI-powered blacklist scanning across 10M+ delivery records.",
    "upgrade_registry": "Upgrade Registry",
    "campaigns": "Campaigns",
    "audience_hub": "Audience Hub",
    "studio": "Studio",
    "intelligence": "Intelligence",
    "launch_campaign": "Launch Campaign",
    "audience": "Audience",
    "message": "Message",
    "preview": "Preview",
    "publish": "Publish",
    "abort_wizard": "Abort Wizard",
    "go_back": "Go Back",
    "launch_engine": "Launch Engine",
    "continue": "Continue",
    "campaign_identity": "Campaign Identity",
    "campaign_title_placeholder": "ENTER CAMPAIGN TITLE...",
    "sms_protocol": "SMS Protocol",
    "whatsapp_engine": "WhatsApp Engine",
    "target_segment": "Target Segment",
    "broadcast_all": "Broadcast to All (1,240 Customers)",
    "creative_copy": "Creative Copy",
    "compose_msg_placeholder": "Compose your campaign message...",
    "dynamic_tokens": "Dynamic Signal Tokens",
    "dispatch_now": "Dispatch Now",
    "schedule": "Schedule",
    "ready_dispatch": "Ready for Dispatch",
    "audience_engine": "Audience Engine",
    "targeting_params": "Global Targeting Parameters",
    "purchase_category": "Purchase Category",
    "order_volume": "Order Volume",
    "last_activity": "Last Activity",
    "geo_location": "Geo Location",
    "success_index": "Success Index",
    "generate_segment": "Generate Segment",
    "customer_segment": "Customer Segment",
    "target_cluster": "Target Cluster",
    "content_studio": "Content Studio",
    "active_templates": "Active Template Schemas",
    "init_template": "Initialize Template",
    "meta_capi": "Meta Conversions API",
    "meta_capi_desc": "Reduce signal loss and boost ROAS by tracking events directly from the server.",
    "engine_control": "Engine Control",
    "strict_validation": "Strict Validation",
    "strict_validation_desc": "Filter out noise by only firing events for strictly validated orders.",
    "high_precision": "High Precision",
    "low_latency": "Low Latency",
    "api_credentials": "API Credentials",
    "auth_protocols": "Authorized Access Protocols",
    "token_expiry_hint": "Server-to-server access tokens expire periodically. Check your dashboard.",
    "admin_command": "Admin Command",
    "customer_suite": "Customer Suite",
    "internal_signals": "Internal Signals",
    "dashboard_telemetry": "Dashboard Telemetry",
    "order_notifications": "Order Notifications",
    "new_signal_alerts": "New Signal Alerts",
    "system_alerts": "System Alerts",
    "critical_engine_status": "Critical Engine Status",
    "external_relay": "External Relay",
    "multichannel_dispatch": "Multi-channel Dispatch",
    "email_distribution": "Email Distribution",
    "sms_dispatch": "SMS Dispatch",
    "engagement_suite": "Engagement Suite",
    "communication_matrix": "Communication Matrix",
    "sms_alert": "SMS Alert",
    "email_alert": "Email Alert",
    "template_identifier": "Template Identifier",
    "order_placed": "Order Placed",
    "order_placed_desc": "Right after order placement",
    "order_confirmed": "Order Confirmed",
    "order_confirmed_desc": "After order verification",
    "order_shipped": "Order Shipped",
    "order_shipped_desc": "Handover to courier",
    "out_for_delivery": "Out for Delivery",
    "out_for_delivery_desc": "When out with rider",
    "delivered_desc": "After successful delivery",
    "cancelled_desc": "When order is cancelled",
    "logic_active": "Logic Active",
    "logic_inactive": "Logic Inactive",
    "email_relay": "Email Relay",
    "dispatch_template": "Dispatch Template",
    "message_content_placeholder": "Message content...",
    "hero_master": "Hero Master",
    "promo_hub": "Promo Hub",
    "action_bar": "Action Bar",
    "trust_panel": "Trust Panel",
    "combo_suite": "Combo Suite",
    "exclusive_collection": "Exclusive Collection",
    "new_arrival": "New Arrival",
    "discover_premium": "Discover our latest premium products...",
    "edit_visuals": "Edit Visuals",
    "cta_text": "CTA Text",
    "slide_description": "Slide Description",
    "link_protocol": "Link Protocol",
    "upload_creative": "Upload Creative",
    "active_banners": "Active Banners",
    "init_banner": "Initialize Banner",
    "trust_badges_hub": "Trust Badges Hub",
    "badge_title": "Badge Title",
    "badge_subtitle": "Badge Subtitle",
    "header_elements_desc": "Control visibility of header elements",
    "show_cat_dropdown": "Show category dropdown in header",
    "promo_anchor": "Promo Anchor",
    "header_highlight_desc": "Highlighted promotional text in header",
    "anchor_text": "Anchor Text",
    "anchor_link": "Anchor Link",
    "link_orchestration": "Link Orchestration",
    "navigation_matrix_desc": "Arrange primary navigation links for your store",
    "label_en": "Label (English)",
    "label_bn": "Label (Bangla)",
    "url_path": "URL Path",
    "new_link": "New Link",
    "media_library": "Media Library",
    "store_customize": "Store Customize",
    "live_updates": "Live Updates",
    // Simplified labels & Unique core translations
    "next": "Next",
    "loading": "Loading...",
    "required": "Required",
    "optional": "Optional",
    "yes": "Yes",
    "no": "No",
    "confirm": "Confirm",
    "success": "Success",
    "error": "Error",
    "name": "Name",
    "phone": "Phone",
    "amount": "Amount",
    "price": "Price",
    "image": "Image",
    "submit": "Submit",
    "update": "Update",
    "refresh": "Refresh",
    "import": "Import",
    "download": "Download",
    "upload": "Upload",
    "settings": "Settings",
    "profile": "Profile",
    "login": "Login",
    "created_at": "Created At",
    "updated_at": "Updated At",
  }
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("bn");

  // Persist language choice
  useEffect(() => {
    const saved = localStorage.getItem("app_lang") as Language;
    if (saved) {
      setLanguage(saved);
      document.documentElement.lang = saved;
    } else {
      document.documentElement.lang = "bn";
    }
  }, []);

  const handleSetLanguage = React.useCallback((lang: Language) => {
    setLanguage(lang);
    localStorage.setItem("app_lang", lang);
    document.documentElement.lang = lang;
  }, []);

  const t = React.useCallback((key: string) => {
    return translations[language][key] || key;
  }, [language]);

  const value = React.useMemo(() => ({
    language,
    setLanguage: handleSetLanguage,
    t
  }), [language, handleSetLanguage, t]);

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
